i=0
for(i<=5):
    score= int(input('score: '))
#int(score)
    if(80<=score<=100):
        print('A')
    elif(75<=score<=79):
        print('B+')
    elif(70<=score<=74):
        print('B')
    elif(65<=score<=69):
        print('C+')
    elif(60<=score<=64):
        print('C')
    elif(55<=score<=59):
        print('D+')
    elif(50<=score<=54):
        print('D')
    elif(0<=score<=49):
        print('F')
    i+=1
